%%----------------HEADER---------------------------%%
%Author:         Tristan Mallet &  Oussema SLEIMI
%Version & Date:   V2 11-09-2015 (dd/mm/yyyy)
%CL=1
%
%
%This program calculate a X that is the real solution of the problem in order to run some tests.
%
% 1. Input:
%
%     dr          = 4x1 double float vector giving the difference between the distance to Jupiter of the actual and reference trajectory at 4 different times.
%     Dvectr      = 4x1 double float vector giving the difference between the corrdinates of the actual and reference trajectory at 4 different times.
%     Dvelocity   = 4x1 double float vector giving the difference between the velocity of the actual and reference trajectory at 4 different times.
%
% 2. Outputs:
%    
%     Xexp  = 19x1  double float vector giving the solution of the problem
%     A  = 19x19 double float vector giving the matrix A (cf NAv-002 for more details).
%     B  = 19x19 double float vector giving the matrix B (cf NAv-002 for more details).

function [Xexp]=Calculate_Xexpected(dr, Dvectr, Dvelocity)


% we define the vector X with value using the actual and reference trajectory at the same 4 times of measurments.
Xexp=[Dvectr(1,1);...
   Dvectr(1,2);...
   Dvectr(1,3);...
   Dvectr(2,1);...
   Dvectr(2,2);...
   Dvectr(2,3);...
   Dvectr(3,1);...
   Dvectr(3,2);...
   Dvectr(3,3);...
   Dvectr(4,1);...
   Dvectr(4,2);...
   Dvectr(4,3);...
   dr(1);...
   dr(2);...
   dr(3);...
   dr(4);...
   Dvelocity(1,1);...
   Dvelocity(1,2);...
   Dvelocity(1,3)];

end