%%----------------HEADER---------------------------%%
%Author:           Tristan Mallet
%Version & Date:   V1 11-09-2015 (dd/mm/yyyy)
%CL=1
%
%
% This program writes the index which noticed all the scenario indications in the index file.
%
% 1. Inputs:
%    VTS text-file : all the scenario-i 
% 2. Outputs:
%   text file index

function [index]=index()

index=fopen('./Inputs/Scenarios/index','w');
fprintf(index,'NAV_Results Version : 1.1\nGenerated by BIRDY NAV TEAM\nDate : %s\n\n', ctime(time()));
	fprintf(index,'OBJECT_NAME : BIRDY\nID_NAME : BIRDY\n');
	
	fprintf(index,'META_START\n\n');

	fprintf(index,"COLUMN #01 : Name of the file\nCOLUMN #02 : Actual trajectory file name\nCOLUMN #03 : Reference trajectory file name\nCOLUMN #04 : Algorithm\nCOLUMN #05 : Sampling file name\nCOLUMN #06 : Corresponding result file name)");

	fprintf(index,'\n\nMETA_STOP\n');
	
scenario_files=readdir('./Inputs/Scenarios');
for i=4:length(scenario_files) # we start at 4 to avoid the undesired files like "." and ".."
	scenario=fopen(strcat('./Inputs/Scenarios/',scenario_files{i}),'r');
	l=' ';
	while 1
		l=fgetl(scenario);
		if strfind(l,'META_STOP')>0 #We start reading the file from the META_STOP tag
			break;
		endif;
	end;
	scenario_num=fgetl(scenario); #Reading of the 6 rows of the considered scenario
	trajectory_name=fgetl(scenario);
	trajectory_name_ephjup=fgetl(scenario);
	algo=fgetl(scenario);
	sampling=fgetl(scenario);
	result_file_name=fgetl(scenario);
	fprintf(index,"%s%60s%60s%15s%15s%25s\n",scenario_num,trajectory_name,trajectory_name_ephjup,algo,sampling,result_file_name);

endfor

fclose(scenario);
fclose(index);

end;